config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  # Routes for Registration Website Blocca.do
  # resources :users, only: [:update, :index]
  get '/auth', to: 'users#index', as: 'auth'
  get 'users/profile'
  get 'users/regenerate'
  get 'users/reactivate'
  get 'users/deactivate'
  get '/docs', to: 'docs#index', as: 'docs'
  get 'pages/index'
  root to: 'pages#index'

  # Routes for Api Blocca.do
  namespace :api, defaults: { format: 'json'} do
    resources :sessions, :only => [:create, :destroy]
    resources :users, :only => [:create, :update, :destroy]
    resources :lists do
      resources :tasks
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true
  validates :auth_token, uniqueness: true

  before_create :generate_authentication_token
  before_create :set_user_role
  before_create do
    set_auth_token_flag(true)
  end

  has_many :lists, dependent: :destroy

  def generate_authentication_token
    self.auth_token = Devise.friendly_token
  end

  def regenerate_token
    generate_authentication_token
    save
  end

  def set_user_role
    self.role = 'member'
  end

  def set_auth_token_flag(flag)
    self.auth_token_flag = flag
  end

  def reactivate_flag
    self.set_auth_token_flag(true)
    save
  end

  def deactivate_flag
    self.set_auth_token_flag(false)
    save
  end

  def admin?
    role=='admin'
  end

  def member?
    role=='member'
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  before_action :authenticate_with_token!

  def index
    respond_with User.all
  end

  def show
    respond_with User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user, status: 201, location: [:api, @user]
    else
      render json: { errors: @user.errors }, status: 422
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      render json: @user, status: 200, location: [:api, @user]
    else
      render json: { errors: @user.errors }, status: 422
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    head 204
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :auth_token, :auth_token_flag)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end

  def regenerate
    @user = current_user
    if @user.regenerate_token
      flash[:notice] = "Auth token updated. Don't forget to update your code!"
      redirect_to auth_path
    else
      flash[:alert] = "Error updating your auth_token. Please try to regenerate again!"
      redirect_to auth_path
    end
  end

  def reactivate
    @user = current_user
    if @user.reactivate_flag
      flash[:notice] = "Your Auth token has been reactivated successfully!"
      redirect_to auth_path
    else
      flash[:alert] = "Error reactivating your auth_token. Please try to reactivate again!"
      redirect_to auth_path
    end
  end

  def deactivate
    @user = current_user
    if @user.deactivate_flag
      flash[:alert] = "Your Auth token has been deactivated. You must reactivate before using!"
      redirect_to auth_path
    else
      flash[:alert] = "Error deactivating your auth_token. Please try to deactivate again!"
      redirect_to auth_path
    end
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password, :auth_token, :auth_token_flag)
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<h1>Users#dashboard</h1>
<p>Find me in app/views/users/dashboard.html.erb</p>

app/views/users/index.html.erb
<div class="row hero logo">
 <%= image_tag("key-logo-horiz.png", :class => "logo", :alt => "key-logo-horiz") %>
  <h3>This is your Auth Token Key.</h3>
  <h5>There are many like it but this one is yours.</h5>
</div>
<% if current_user.auth_token_flag == true %>
  <div class="row well">
    <h2 class="col-3 key-code"><%= @user.auth_token %></h2>
    <div class="col-3 push-right-5 key-toggle">
        <%= link_to "Regenerate Key", users_regenerate_path, class: "btn primary"%>
        <%= link_to "Deactivate Key", users_deactivate_path, class: "btn secondary"%>
    </div>
  </div>
   <div class="row help">If you feel your key has been compromised, click regenerate to delete your current key and populate a new one.</div>
   <div class="row actions" data-no-turbolink>
     <%= link_to "Now, learn how to use it", docs_path, class: "btn btn-wide thirdy"%>
   </div>
<% else %>
  <div class="row well">
    <h2 class="col-3 key-code deactive"><%= @user.auth_token %></h2>
    <div class="col-3 push-right-5 key-toggle">
      <%= link_to "Reactivate Key", users_reactivate_path, class: "btn btn-wide thirdy "%>
    </div>
  </div>
   <div class="row help deactive">Your Auth Token has been deactivated! None of your apps will work until you reactivate the Auth Token.</div>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>