config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  # Routes for Registration Website Blocca.do
  # resources :users, only: [:update, :index]
  get '/auth', to: 'users#index', as: 'auth'
  get 'users/profile'
  get 'users/regenerate'
  get 'users/reactivate'
  get 'users/deactivate'
  get '/docs', to: 'docs#index', as: 'docs'
  get 'pages/index'
  root to: 'pages#index'

  # Routes for Api Blocca.do
  namespace :api, defaults: { format: 'json'} do
    resources :sessions, :only => [:create, :destroy]
    resources :users, :only => [:create, :update, :destroy]
    resources :lists do
      resources :tasks
    end
  end
end

app/views/pages/index.html.erb
 <div class="hero">
  <%= image_tag("checkmark-logo.png", :class => "logo", :alt => "checkmark-logo") %>
  <h1>Blocca.do</h1>
  <h3>What are you going to-do today?</h3>
  <h5>The world's most powerful API for managing to-do lists.</h5>
  <ul id="start" class="button-bar" data-no-turbolink>
    <li><a href="#signupform" class="btn primary">Get Started</a></li>
    <li><%= link_to "API Docs", docs_path, {:class => "btn secondary"} %></li>
  </ul>
</div>
<div class="sign-up">
  <div class="intro">
    <h1><a name="signupform">4,487 apps blocca.do-it.</a></h1>
    <h3>As of last week, 87,640,731,001 to-dos were blocca.do-ne.</h3>
    <h5>No credit card required. Just fill out the form below and you're in!</h5>
  </div>
  <div class="row">
    <div class="col-2">
      <%= image_tag("phone.png", :class=>"phone", :alt => "checkmark-logo") %>
    </div>
    <div class="col-4">
      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-group top">
          <%= f.input :name, required: true, placeholder: "George Washington" %>
        </div>
        <div class="form-group">
          <%= f.input :email, required: true, placeholder: "Your.email.address@email.com" %>
        </div>
        <div class="form-group">
          <%= f.input :password, required: true, hint: "7 characters minimum. No emojis allowed." %>
        </div>
        <div class="form-group">
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Sign me up and get me my key", class: "btn btn-wide thirdy" %>
          <small class="note">By submitting your information you are agreeing to our Terms & Conditions.</small>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/signin.html.erb
<div class="hero">
  <%= image_tag("key-logo.png", :class => "logo", :alt => "key-logo") %>
  <h1>Blocca.do</h1>
  <div class="sign-in">
    <%= render "devise/sessions/sign_in" %>
  </div>
</div>
<div class="sign-up">
  <div class="intro">
    <h1><a name="signupform">Forgot your password?</a></h1>
    <h3>Don't worry it happens to the best of us. We got this.</h3>
    <h5>Just enter your email in the form below and you're set!</h5>
  </div>
  <div class="row">
    <div class="forgot">
      <%= render "devise/passwords/forgot" %>
    </div>
  </div>
</div>