config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  # Routes for Registration Website Blocca.do
  # resources :users, only: [:update, :index]
  get '/auth', to: 'users#index', as: 'auth'
  get 'users/profile'
  get 'users/regenerate'
  get 'users/reactivate'
  get 'users/deactivate'
  get '/docs', to: 'docs#index', as: 'docs'
  get 'pages/index'
  root to: 'pages#index'

  # Routes for Api Blocca.do
  namespace :api, defaults: { format: 'json'} do
    resources :sessions, :only => [:create, :destroy]
    resources :users, :only => [:create, :update, :destroy]
    resources :lists do
      resources :tasks
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocca.do</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <div class="row">
      <% if current_user %>
      <%= link_to(auth_path) do %>
        <%= image_tag("blocca-logo.png", :class => "blocca-logo left", :alt => "blocca.do-logo") %>
      <% end %>
      <ul class="left site-nav" data-no-turbolink>
          <li><%= link_to "Auth Token Key", auth_path %></li>
          <li><%= link_to "API Docs", docs_path %></li>
      <% else %>
      <ul class="left">
          <li><div class="today">Today is <%= day %>.</div></li>
      <% end %>
      </ul>
      <ul id="nav" class="right user-info" data-no-turbolink>
        <% if current_user %>
              <li>Hello, <%= current_user.name %>! | <%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
           <% else %>
              <li><%= link_to "Welcome", root_path, {:class=>'active'} %></li>
              |
              <li><%= link_to "Sign In", new_user_session_path %></li>
              |
              <li><%= link_to "Sign up", root_path(:anchor=>'signupform') %></li>
          <% end %>
      </ul>
    </div>
  </div>
  <div class="container">
    <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
   <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
     </div>
   <% end %>
    <%= yield %>
  </div>
  <div class="footer">
    <div class="row">
      <h3 class="counter col-6">144,444,877,640,001,711,031 to-dos smashed and counting!</h3>

      <p class="copyright col-6">
        <bold>Not-so-fine print:</bold> <u>Terms of service</u>, <u>privacy policy</u>, <u>refund policy</u>, <u>security information</u>, <u>% uptime</u>, <u>system status</u>.
      </p>

      <p class="social-media"><%= image_tag("twitter.png", :class => "twitter", :alt => "twitter-share") %><%= image_tag("facebook.png", :class => "facebook", :alt => "facebook-share") %></p>

      <p class="legal col-6">All text & design copyright &copy2015 blocca.do.com. All rights reserved.</p>
    </div>
  </div>
</body>
</html>